# Generated by Django 3.2.9 on 2021-11-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_laptop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(blank=True, choices=[(1, 'Apple'), (2, 'Asus'), (3, 'Dell'), (4, 'Lenovo'), (5, 'Acer')], max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='color',
            field=models.CharField(blank=True, choices=[(1, 'Grey'), (2, 'Silver'), (3, 'Black'), (4, 'Red'), (4, 'Blue')], max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display',
            field=models.CharField(blank=True, choices=[(1, '4096 x 2160'), (2, '2048 x 1080'), (3, '1920 x 1080'), (4, '1024 x 768')], max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='prod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='vin',
            field=models.IntegerField(blank=True),
        ),
    ]
